name: Code check
on: [push]
# on:
  # workflow_dispatch:
  # pull_request:
  #   branches:
  #     - chore/tag-releases
  #   types: [closed]
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install and lint
        run: |
          git config --global url."https://".insteadOf git://
          yarn install
          yarn lint
          git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/docknetwork/react-native-sdk.git" ../wallet-sdk
          yarn --cwd ../wallet-sdk install
          yarn sync-sdk

      - name: Unit tests
        run: |
          yarn test

      - name: Install AWS
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.S3_REGION }}

      - name: Copy APK from s3 bucket
        run: |
          aws s3 cp s3://${{ secrets.S3_APP_BUCKET }}/${{ secrets.S3_ANDROID_APK_DIR }}/${{ github.event.head_commit.message }}/app-release.apk ./
          ls ./

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GIT_ACCESS_TOKEN }}
          file: ./app-release.apk
          asset_name: dock-wallet.apk
          tag: ${{ github.event.head_commit.message }}
          overwrite: true
          body: ${{ github.event.head_commit.message }}
