name: Code check
on: [push]
# on:
  # workflow_dispatch:
  # pull_request:
  #   branches:
  #     - chore/tag-releases
  #   types: [closed]
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # - name: Setup node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '16.x'

      # - name: Install and lint
      #   run: |
      #     git config --global url."https://".insteadOf git://
      #     yarn install
      #     yarn lint
      #     git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/docknetwork/react-native-sdk.git" ../wallet-sdk
      #     yarn --cwd ../wallet-sdk install
      #     yarn sync-sdk

      # - name: Unit tests
      #   run: |
      #     yarn test
      - name: Install AWS
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.S3_REGION }}
      - name: List s3 files
        run: |
          aws s3 ls
      #  S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      #     S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      #     S3_APP_BUCKET: ${{ secrets.S3_APP_BUCKET }}
      #     S3_REGION: ${{ secrets.S3_REGION }}
      #     S3_ANDROID_APK_DIR: ${{ secrets.S3_ANDROID_APK_DIR }}
      #     S3_ACL: ${{ secrets.S3_ACL }}

      
      # - uses: rickstaa/action-create-tag@v1
      #   with:
      #     tag: ${{ github.event.head_commit.message }}
      #     message: ${{ github.event.head_commit.message }}
      
